language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'import Pkg; Pkg.clone(pwd(), "Bobby"); Pkg.build("Bobby"); Pkg.test("Bobby"; coverage=true)'
after_success:
  - echo "done!"
  - julia -e 'import Pkg; cd(Pkg.dir("Bobby")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
matrix:
  fast_finish: true